# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lockstep < Formula
  desc "Secure credential management CLI for developers and teams"
  homepage "https://github.com/joshuapare/lockstep"
  version "0.0.4"
  license "MIT"

  on_macos do
    url "https://github.com/joshuapare/lockstep/releases/download/v0.0.4/lockstep-cli_0.0.4_darwin_all.tar.gz"
    sha256 "acf0ae29eb893ae4e74f0180908a9e925a94ce10926ba60dea3027c74011cb5f"

    def install
      bin.install "credctl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshuapare/lockstep/releases/download/v0.0.4/lockstep-cli_0.0.4_linux_amd64.tar.gz"
      sha256 "a28cdfbf715d412a7d18822c7ffbe7688bd0c3659f7e274751c144a35631b613"
      def install
        bin.install "credctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshuapare/lockstep/releases/download/v0.0.4/lockstep-cli_0.0.4_linux_arm64.tar.gz"
      sha256 "735391ad978071299834de975e4d2ec6749ff3f318159f5848f382bb275a6b3e"
      def install
        bin.install "credctl"
      end
    end
  end

  test do
    system "#{bin}/credctl", "version"
  end
end
