# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lockstep < Formula
  desc "Secure credential management CLI for developers and teams"
  homepage "https://github.com/joshuapare/lockstep"
  version "0.0.8"
  license "MIT"

  on_macos do
    url "https://github.com/joshuapare/homebrew-tap/releases/download/lockstep-v0.0.8/lockstep-cli_0.0.8_darwin_all.tar.gz"
    sha256 "86d34192798a259848e5e8db63c8928163e075407f52597a071dd196521e892e"

    def install
      bin.install "credctl"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshuapare/homebrew-tap/releases/download/lockstep-v0.0.8/lockstep-cli_0.0.8_linux_amd64.tar.gz"
      sha256 "71da349346780d884152c93dc6db102a4d589b3e4b538db878a01bb4747bb6cd"
      def install
        bin.install "credctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/joshuapare/homebrew-tap/releases/download/lockstep-v0.0.8/lockstep-cli_0.0.8_linux_arm64.tar.gz"
      sha256 "9d43c6be6a8822e42ccba818089074a2bfce9a475dd7194f13cd544469b543a9"
      def install
        bin.install "credctl"
      end
    end
  end

  def caveats
    <<~EOS
      On macOS, use the cask instead for both CLI and desktop app:
        brew install --cask joshuapare/tap/lockstep
    EOS
  end

  test do
    system "#{bin}/credctl", "version"
  end
end
